/**
 * Pull every Lucide icon the React build actually rendered out of the
 * pre-rendered HTML, and write them as a PHP map the WordPress theme can use.
 *
 * Taking the icons from the rendered output rather than re-deriving them from
 * the npm package guarantees the WordPress site draws the *same* glyphs the
 * client already approved — no version drift, no missing icon.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const DIST = process.argv[2] || '/var/lib/freelancer/projects/40683296/build/dist'
const OUT = process.argv[3] || '/var/lib/freelancer/projects/40683296/wp/themes/trg-networking/inc/icons.php'

function htmlFiles(dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry)
    if (statSync(p).isDirectory()) htmlFiles(p, acc)
    else if (entry.endsWith('.html')) acc.push(p)
  }
  return acc
}

const icons = new Map()

// Icons that only appear after a user interaction (an open FAQ row, an open
// mobile drawer) never make it into the pre-rendered HTML, so they are supplied
// here. Kept identical to Lucide's own 24x24 outlines.
const INTERACTIVE_ONLY = {
  minus: '<path d="M5 12h14"/>',
  x: '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
  'chevron-right': '<path d="m9 18 6-6-6-6"/>',
  'circle-check': '<circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/>',
  'triangle-alert': '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
  // Added for the two service areas the change request introduced (network
  // infrastructure, strategic IT / vCIO). No page of the source build used
  // them, so they cannot be scraped out of dist/.
  network:
    '<rect x="16" y="16" width="6" height="6" rx="1"/><rect x="2" y="16" width="6" height="6" rx="1"/><rect x="9" y="2" width="6" height="6" rx="1"/><path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"/><path d="M12 12V8"/>',
  compass:
    '<path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z"/><circle cx="12" cy="12" r="10"/>',
}

for (const [name, inner] of Object.entries(INTERACTIVE_ONLY)) icons.set(name, inner)

for (const file of htmlFiles(DIST)) {
  const html = readFileSync(file, 'utf8')
  // Non-greedy match on a whole <svg>…</svg>; lucide SVGs never nest.
  const re = /<svg\b[^>]*class="lucide lucide-([a-z0-9-]+)[^"]*"[^>]*>([\s\S]*?)<\/svg>/g
  let m
  while ((m = re.exec(html))) {
    const [, name, inner] = m
    if (!icons.has(name)) icons.set(name, inner.trim())
  }
}

const names = [...icons.keys()].sort()

const php = `<?php
/**
 * Lucide icon set, extracted from the approved React build so the WordPress
 * site draws identical glyphs. Generated by tools/extract-icons.mjs — if you
 * need a new icon, add it here rather than loading an icon font.
 *
 * Usage: trg_icon( 'check', 16, 'text-brand-600' )
 *
 * @package TRG_Networking
 */

defined( 'ABSPATH' ) || exit;

/**
 * Inner markup for every icon, keyed by Lucide name.
 *
 * @return array<string,string>
 */
function trg_icon_paths() {
\treturn array(
${names.map((n) => `\t\t'${n}' => '${icons.get(n).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\s+/g, ' ')}',`).join('\n')}
\t);
}

/**
 * Echo an inline SVG icon.
 *
 * Icons here are decorative: every one is paired with visible text, so they are
 * hidden from screen readers rather than given a label that would be read twice.
 *
 * @param string $name  Lucide icon name.
 * @param int    $size  Pixel size for width and height.
 * @param string $class Extra CSS classes.
 */
function trg_icon( $name, $size = 16, $class = '' ) {
\t$paths = trg_icon_paths();
\tif ( ! isset( $paths[ $name ] ) ) {
\t\treturn;
\t}
\tprintf(
\t\t'<svg xmlns="http://www.w3.org/2000/svg" width="%1\$d" height="%1\$d" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-%2\$s %3\$s" aria-hidden="true" focusable="false">%4\$s</svg>',
\t\t(int) $size,
\t\tesc_attr( $name ),
\t\tesc_attr( $class ),
\t\t$paths[ $name ] // phpcs:ignore WordPress.Security.EscapeOutput -- static SVG markup from a generated file.
\t);
}

/**
 * Return the icon markup instead of echoing it.
 *
 * @param string $name  Lucide icon name.
 * @param int    $size  Pixel size.
 * @param string $class Extra CSS classes.
 * @return string
 */
function trg_get_icon( $name, $size = 16, $class = '' ) {
\tob_start();
\ttrg_icon( $name, $size, $class );
\treturn ob_get_clean();
}
`

writeFileSync(OUT, php, 'utf8')
console.log(`${names.length} icons written to ${OUT}`)
console.log(names.join(', '))
